blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from myblog.sitemaps import PostSiteMap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts' : PostSiteMap,}

admin.site.site_header = "Robs blog admin"
admin.site.site_title = "Robs blog admin site"
admin.site.index_title = "Robs blog Admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls', namespace='myblog')),
    path('myblog/sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/myblog/urls.py
from django.urls import path
from . import views
from django.views.generic.dates import ArchiveIndexView
from .models import Post

app_name = 'myblog'

urlpatterns = [

    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('gallery/', views.gallery_list, name='gallery_list'),
    path('<slug:gallery>/<int:pk>', views.gallery_detail, name='gallery_detail'),
    path('contact/', views.contact_form, name='contact_form'),
    path('archive/',
         ArchiveIndexView.as_view(model=Post, date_field="created"),
         name="post_archive"),
    path('purchase/', views.purchase_page, name='purchase'),



    ]

blog/myblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.urls import reverse
from taggit.managers import TaggableManager
from exiffield.fields import ExifField
from exiffield.getters import exifgetter
from PIL import Image
from django_resized import ResizedImageField
from blog.settings import DEFAULT_FILE_STORAGE
from os.path import join as pjoin
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit, Resize, ResizeToFill,ResizeToCover, SmartResize
from pilkit.processors import Thumbnail
from django.core.files.storage import default_storage as storage
from ckeditor.fields import RichTextField

#test


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class FeaturedManager(models.Manager):
    def get_queryset(self):
        return super(FeaturedManager, self).get_queryset().filter(featured=True, status='published')


class Author(models.Model):

    name = models.CharField(max_length=300, null=True, blank=False)
    email = models.EmailField(max_length=70,blank=True,unique=True)
    bio = models.TextField(max_length=200, null=True, blank=True)
    photo = ResizedImageField(size=[500, 400], upload_to='authors', default='author pic')
    bio = models.TextField(max_length=1000, null=True, blank=True)
    bio_image = ResizedImageField(size=[2000, 1000], upload_to='bio', default='bio_pic')
    Facebook_link = models.TextField(max_length=1000, null=True, blank=True)
    Twitter_link = models.TextField(max_length=1000, null=True, blank=True)
    Instagram_link = models.TextField(max_length=1000, null=True, blank=True)


    def __str__(self):
        return self.name

    @mark_safe
    def author_thumbnail(self):
        return u'<img src="%s" height="65px" />' % (self.photo.url)

    author_thumbnail.short_description = 'Thumbnail'
    author_thumbnail.allow_tags = True



class Post(models.Model):
    STATUS = (
        ('published', 'Published'),
        ('unpublished', 'Unpublished'),
    )

    title = models.CharField(max_length=250, null=False, blank=False)
    summary = models.CharField(max_length=100, blank=True)
    slug = models.SlugField(unique_for_date='publish')
    author = models.ForeignKey(Author, on_delete=models.CASCADE,
                               related_name='blog_posts', null=True)
    cover = models.ForeignKey('Photo', on_delete=models.SET_NULL, null=True, related_name='cover')

    body = RichTextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    edited = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS, default='unpublished')
    featured = models.BooleanField(default=False)
    comments_option = models.BooleanField(default=True)
    objects = models.Manager()
    published = PublishedManager()
    feature = FeaturedManager()
    tags = TaggableManager(verbose_name="Add Tags", help_text="Use comma to separate")


    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title



    def get_absolute_url(self):
        return reverse('myblog:post_detail', args=[self.publish.year,
                                                   self.publish.month,
                                                   self.publish.day,
                                                   self.slug])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Catagory(models.Model):
    name = models.CharField(max_length=200, null=True)
    slug = models.SlugField(null=True)
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Description')

    class Meta:
        verbose_name_plural = 'Catagory'

    def __str__(self):
        return str(self.name)


class Album(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique_for_date='created', null=True)
    public = models.BooleanField(default=False)
    thumb =  models.ForeignKey('Photo', on_delete=models.SET_NULL,
                               related_name='thumbs', null=True )
    categories = models.ForeignKey(Catagory, on_delete=models.CASCADE, null=True, blank=True)
    summary = models.CharField(max_length=200, blank=True)




    def get_absolute_url(self):
        return reverse('myblog:gallery_detail', args=[self.slug,
                                                      self.pk])


    def __str__(self):
        return self.title



    @mark_safe
    def images(self):
        lst = [x.image.name for x in self.photos.all()]
        lst = ["<a href='/media/%s'>%s</a>" % (x, x.split('/')[-1]) for x in lst]
        return ",".join(lst)

    images.allow_tags = True






class Photo(models.Model):
    image = models.ImageField(upload_to='images')
    mid_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(220, 150)],
                                      format='JPEG',
                                      options={'quality': 100})
    gallery_thumbnail = ImageSpecField(source='image',
                                   processors=[ResizeToFit(300, 250)],
                                   format='JPEG',
                                   options={'quality': 100})
    gallery_detail = ImageSpecField(source='image',
                                       processors=[ResizeToFit(1000, 850)],
                                       format='JPEG',
                                       options={'quality': 100})
    title = models.CharField(max_length=100)
    albums = models.ManyToManyField(Album, blank=True, related_name='photos')
    feature_image = models.BooleanField(default=False)
    description = models.CharField(editable=False, max_length=150, blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name='pictures')

    lens = models.TextField(editable=False, max_length=100, default='Lens Data')
    caption = models.CharField(editable=False, max_length=1000, default='Caption info')
    file_size = models.CharField(editable=False, max_length=20, default='File_size')
    width = models.IntegerField(blank=True, null=True, editable=False)
    height = models.IntegerField(blank=True, null=True, editable=False)
    categories = models.ForeignKey(Catagory, on_delete=models.CASCADE, null=True, blank=True)
    objects = models.Manager
    info = models.TextField(default='**info empty**', blank=True, help_text="editable caption info no reversable")
    exif = ExifField(source='image', denormalized_fields={'lens': exifgetter('LensID'),
                                                          'caption': exifgetter('Description'),
                                                          'file_size': exifgetter('FileSize'),
                                                          'description': exifgetter('Headline')

                                                          })


    def save(self, *args, **kwargs):
        super(Photo, self).save(*args, **kwargs)
        """Get EXIF"""
        im = Image.open(self.image)
        try:
            info = im.getexif()[0x010e]
            self.info = info
        except KeyError:
            pass
        super(Photo, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def albums_(self):
        lst = [x[1] for x in self.albums.values_list()]
        return ",".join(lst)

    def size(self):
         return "%s x %s" % (self.width, self.height)

blog/myblog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()



class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment, Photo, Album, Author
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm, ContactForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.views.generic.dates import ArchiveIndexView
from django.contrib import messages




def purchase_page(request):
    return render(request, 'post/purchase.html')








def contact_form(request):
    contact = Author.objects.get(name='Robert Melen')
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            send_mail(name, message, email, ['admin@blog.com'])
            messages.success(request, 'Your message has been sent, I will reply asap!')
            return HttpResponseRedirect(request.path_info)

    return render(request, 'post/contact_form.html', {'form': form,
                                                      'contact': contact})







#blog post views


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # list of active comments for this post
    comments = post.comments.filter(active=True)
    paginator = Paginator(comments, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #create comment object but dont save to database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            #save the comment to the database
            new_comment.save()
            messages.success(request, 'Your message has been sent, I will reply asap!.')
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'post/detail.html',
                  {'post': post,
                   'posts' : posts,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts,
                   })


class PostFeaturedView(ListView):
    queryset = Post.feature.all()
    context_object_name = 'featured'
    paginate_by = 3
    template_name = 'post/featured.html'


#form views

def post_share(request, post_id):
    #retrieve posts by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        #form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #form fields pass validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                          f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else: #.....send email
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                                'form': form,
                                                'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')

            search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query),
                                              ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'post/search.html',
                  {'form' : form,
                   'query' : query,
                   'results' : results})



def gallery_list(request):
    gallery = Album.objects.filter(public=True)
    paginator = Paginator(gallery, 4)
    page = request.GET.get('page')
    try:
        galleries = paginator.page(page)
    except PageNotAnInteger:
        galleries = paginator.page(1)
    except EmptyPage:
        galleries = paginator.page(paginator.num_pages)

    return render(request, 'gallery/gallery_list.html', {

        'galleries': galleries,
        })


def gallery_detail(request, gallery, pk):

    gallery = get_object_or_404(Album, slug=gallery, pk=pk)
    images = gallery.photos.all()
    return render(request,  'gallery/gallery_detail.html', {
                  'gallery': gallery,
    'images': images
    })

blog/myblog/templates/post/contact_form.html
{% extends "blog/base.html" %}
{% block header %}
{% endblock %}
{% block content %}
<body>
<div class="container">
    <div class="row">
        <div class="twelve columns" style="padding-bottom: 8rem;">
            <h1>About/Contact Info</h1>
                Socials/Email :
                <a href="{{ contact.Twitter_link }}" target="_blank" title="Facebook Page"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="{{ contact.Facebook_link }}" title="Facebook Page"><i class="fab fa-facebook fa-2x"></i></a>
                <a href="{{ contact.Instagram_link }}" title="Facebook Page"><i class="fab fa-instagram fa-2x"></i></a>/
                robert_melen@yahoo.co.uk
        </div>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        {% if message.tags %} {{ message.tags }} {% endif %}<h3>{{ message }}</h3>
    {% endfor %}
{% endif %}
<div class="container">
    <div class="row">
        <div class="one-half column">
            <hr>
           <img src="{{ MEDIA_URL }}{{ contact.bio_image.url }}"  style="width: 90%; height: auto;">
        </div>
        <div class="one-half column">
            <hr>
            <h3>About/What I do</h3>
            <h6>{{ contact.bio }}</h6>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="twelve columns" style="padding-top: 7rem;">
           <h6>You can send me a messge via this form</h6>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Send email">
            </form>
        </div>
    </div>
</div>
{% endblock %}
</body>

blog/myblog/templates/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{{ post.title }}{% endblock %}
{% block header %}{% endblock %}
{% block featured %}{% endblock %}
{% block sticky %}{% endblock %}
{% load social_share %}
{% block content %}
<div style="position:relative; top:-4rem;">
    <br>
    <br>
   </div>

<div class="container" >
    <div><h1 style=" border-bottom: 2px #228B22 solid; position:relative; top:-5rem">{{ post.title }}</h1></div>
    <p >
<div style=" margin-top: -20px;font-size: 1.6vmin; position:relative; top:-5rem "><h6>Written by {{ post.author }}
            <img src="{{ post.author.photo.url }}"
                 style="max-height: 20px; border-radius: 50%;"/>/published on {{ post.publish }}</div>


<div style="position:relative; top:-4rem;"><strong>Summary/{{ post.summary }}</strong> </div>
    </p>
      <div style="position:relative; top:-4rem;">Share
    {% post_to_facebook object_or_url '<i class="fab fa-facebook" style="display: inline;"></i>' %}
     {% post_to_twitter '<i class="fab fa-twitter"></i>' object_or_url '<i class="fab fa-twitter"></i>' %}</div>
</div >
                {% if messages %}

                        {% for message in messages %}
                        {% if message.tags %} {{ message.tags }} {% endif %}<h3>{{ message }}</h3>
                {% endfor %}

                {% endif %}



    <div class="row" >
        <div class="twelve columns" style="">
                {{ post.body|markdown }}
                 <div><a href="{% url 'myblog:post_share' post.id %}">

                                        </a>
                 </div>
        </div>
    </div>
</div>
<hr>
<br/>
<br/>
<br/>

<div class="container">
    <div class="row">
        <div class="twelve columns" style="text-align:center;" >
<h6>Similar posts</h6>
{% for post in similar_posts %}
    <div style="display: inline-block; padding: 0px 10px; margin-bottom: 4rem;">
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </div>
{%  empty %}

{% endfor %}
{% if post.comments_option %}
<div>
{% with comments.count as total_comments %}
    <h5>
        {{ total.comments }} Comments{{ total_comments|pluralize }}
    </h5>
{% endwith %}

{% for comment in posts %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
        <hr>
    </div>


{% empty %}
    <p>There are no comments yet</p>
{% endfor %}
{% include "pagination.html" with page=posts %}
{% if new_comment %}

{% else %}
        </div>
    </div>
</div>
    <div class="form-box">
    <h4>Add a comment about this post</h4>
    <form method="post">
        <label class="label">Name</label>
        {% render_field comment_form.name class="input" placeholder="Your name" %}
        <label class="label">Email</label>
        {% render_field comment_form.email class="input" placeholder="example@example.com" %}
        <label class="label">Message</label>
        {% render_field comment_form.body class="textarea" placeholder="This post is...." %}
        {% csrf_token %}
        <p><input class="button-primary" type="submit" value="Submit" />

    </form>

    </div>

{% endif %}
{% else %}
<h6>Comments are disabled for this post</h6>
{% endif %}
{% endblock %}

blog/myblog/templates/post/feature_image.html
{% for images in image %}
<img src="{{ MEDIA_URL }}{{ images.image.url }}" style="max-height: 200px;"/>
{% endfor %}

blog/myblog/templates/post/featured.html
{% extends "blog/base.html" %}
{% block title %}{% endblock %}
{% block content %}
{% for post in featured %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h4>
    <p>
        <small><em>Published {{ post.publish }} by {{ post.author }}</small></em>
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/myblog/templates/post/featured_posts.html
<h6 style="display: inline-block">
    {% for post in featured_posts %}
        <a class="button" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {% endfor %}
</h6>

blog/myblog/templates/post/latest_posts.html
<H6>
    {% for post in latest_posts %}
        <a class="button" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {% endfor %}
</H6>

blog/myblog/templates/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>Latest Posts</h1>
{% if tag %}
<h2 xmlns="http://www.w3.org/1999/html">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            {% include "pagination.html" with page=posts %}
    {% for post in posts %}
    <h5>

        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
            <div style="-webkit-box-shadow: -1px 9px 18px 0px rgba(0,0,0,0.75);">
                <img src="{{ media_url }}{{ post.cover.gallery_detail.url }}" style=" max-width:80%; height:auto;">
            </div>
        </a>
    </h5>

    <p>
        <small><em>Published {{ post.publish }} by {{ post.author }}</small></em>
    </p>
    {{ post.body|markdown|truncatewords:15 }}
    <hr style="width : 15%; border-color: #123455">

<div>
    <p class="tags"><h7>Tags:</h7>
        {% for tag in post.tags.all %}
            <a href="{% url "myblog:post_list_by_tag" tag.slug %}"> {{ tag.name }}"
                </a>
                {% if not forloop.last %},{% endif %}
                {% endfor %}
    </p>
    <hr>
</div>
            {% endfor %}
            <a class="button" href="#">Top of Page</a>
            {% endblock %}

blog/myblog/templates/post/photo_list.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static "css/normalize.css" %}"rel="stylesheet">
    <link href="{% static "css/skeleton.css" %}"rel="stylesheet">
    <link href="{% static "css/gh.css" %}"rel="stylesheet">
    <link href="{% static "css/custom.css" %}"rel="stylesheet">

</head>
{% include "blog/nav_bar.html" %}
<body>
<div class="container">
    <div class="row">
        <div class="four columns">
            <h1>Gallery</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="twelve columns">
              {% for pic in photo %}
            <h2 style="padding: 5px;">{{ pic.title }}</h2>
            <img src=" {{ pic.image.url }}" class="u-img-responsive" style="padding: 10px;">
            <h6>{{ pic.info }}</h6>
            {% endfor %}
        </div>
    </div>
</div>
</body>
{% include "blog/js.html" %}
</html>

blog/myblog/templates/post/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/myblog/templates/post/purchase.html
{% extends "blog/base.html" %}
{% block header %}{% endblock %}
{% block content %}
<h6>I will be adding system to license and purchase images via this website ASAP.
    in the meantime please <a href="{% url 'myblog:contact_form' %}"><i>contact</i></a> me for usage or personal use.<h6/>

<hr>

    <h6>On he subject of pictures! All images are my lawful copyright and cannot be used without permission
    in any format, that includes social media. Any breaches in copyright will be acted upton.<h6/>
{% endblock %}

blog/myblog/templates/post/search.html
{% extends "blog/base.html" %}
{% load widget_tweaks %}
{% load blog_tags %}
{% block header %}{% endblock %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} results{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>There are no results</p>
        {% endfor %}
        <p><a href="{% url "myblog:post_search" %}">Search again</a></p>
    {% else %}
        <h4>Search posts</h4>
    <div class="container">
        <div class="row">
            <div class="twelve columns">
        <form method="get">
            <label class="label">Search</label>
            {% render_field form.query class="input" placeholder="Enter search term" %}
            <input type="submit" value="Search">
        </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

blog/myblog/templates/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was succefully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}