blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from myblog.sitemaps import PostSiteMap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts' : PostSiteMap,}

admin.site.site_header = "Robs blog admin"
admin.site.site_title = "Robs blog admin site"
admin.site.index_title = "Robs blog Admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls', namespace='myblog')),
    path('myblog/sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/myblog/urls.py
from django.urls import path
from . import views
from django.views.generic.dates import ArchiveIndexView
from .models import Post

app_name = 'myblog'

urlpatterns = [

    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('gallery/', views.gallery_list, name='gallery_list'),
    path('<slug:gallery>/<int:pk>', views.gallery_detail, name='gallery_detail'),
    path('contact/', views.contact_form, name='contact_form'),
    path('archive/',
         ArchiveIndexView.as_view(model=Post, date_field="created"),
         name="post_archive"),
    path('purchase/', views.purchase_page, name='purchase'),



    ]

blog/myblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.urls import reverse
from taggit.managers import TaggableManager
from exiffield.fields import ExifField
from exiffield.getters import exifgetter
from PIL import Image
from django_resized import ResizedImageField
from blog.settings import DEFAULT_FILE_STORAGE
from os.path import join as pjoin
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit, Resize, ResizeToFill,ResizeToCover, SmartResize
from pilkit.processors import Thumbnail
from django.core.files.storage import default_storage as storage
from ckeditor.fields import RichTextField

#test


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class FeaturedManager(models.Manager):
    def get_queryset(self):
        return super(FeaturedManager, self).get_queryset().filter(featured=True, status='published')


class Author(models.Model):

    name = models.CharField(max_length=300, null=True, blank=False)
    email = models.EmailField(max_length=70,blank=True,unique=True)
    bio = models.TextField(max_length=200, null=True, blank=True)
    photo = ResizedImageField(size=[500, 400], upload_to='authors', default='author pic')
    bio = models.TextField(max_length=1000, null=True, blank=True)
    bio_image = ResizedImageField(size=[2000, 1000], upload_to='bio', default='bio_pic')
    Facebook_link = models.TextField(max_length=1000, null=True, blank=True)
    Twitter_link = models.TextField(max_length=1000, null=True, blank=True)
    Instagram_link = models.TextField(max_length=1000, null=True, blank=True)


    def __str__(self):
        return self.name

    @mark_safe
    def author_thumbnail(self):
        return u'<img src="%s" height="65px" />' % (self.photo.url)

    author_thumbnail.short_description = 'Thumbnail'
    author_thumbnail.allow_tags = True



class Post(models.Model):
    STATUS = (
        ('published', 'Published'),
        ('unpublished', 'Unpublished'),
    )

    title = models.CharField(max_length=250, null=False, blank=False)
    summary = models.CharField(max_length=100, blank=True)
    slug = models.SlugField(unique_for_date='publish')
    author = models.ForeignKey(Author, on_delete=models.CASCADE,
                               related_name='blog_posts', null=True)
    cover = models.ForeignKey('Photo', on_delete=models.SET_NULL, null=True, related_name='cover')

    body = RichTextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    edited = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS, default='unpublished')
    featured = models.BooleanField(default=False)
    comments_option = models.BooleanField(default=True)
    objects = models.Manager()
    published = PublishedManager()
    feature = FeaturedManager()
    tags = TaggableManager(verbose_name="Add Tags", help_text="Use comma to separate")


    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title



    def get_absolute_url(self):
        return reverse('myblog:post_detail', args=[self.publish.year,
                                                   self.publish.month,
                                                   self.publish.day,
                                                   self.slug])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Catagory(models.Model):
    name = models.CharField(max_length=200, null=True)
    slug = models.SlugField(null=True)
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Description')

    class Meta:
        verbose_name_plural = 'Catagory'

    def __str__(self):
        return str(self.name)


class Album(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique_for_date='created', null=True)
    public = models.BooleanField(default=False)
    thumb =  models.ForeignKey('Photo', on_delete=models.SET_NULL,
                               related_name='thumbs', null=True )
    categories = models.ForeignKey(Catagory, on_delete=models.CASCADE, null=True, blank=True)
    summary = models.CharField(max_length=200, blank=True)




    def get_absolute_url(self):
        return reverse('myblog:gallery_detail', args=[self.slug,
                                                      self.pk])


    def __str__(self):
        return self.title



    @mark_safe
    def images(self):
        lst = [x.image.name for x in self.photos.all()]
        lst = ["<a href='/media/%s'>%s</a>" % (x, x.split('/')[-1]) for x in lst]
        return ",".join(lst)

    images.allow_tags = True






class Photo(models.Model):
    image = models.ImageField(upload_to='images')
    mid_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(220, 150)],
                                      format='JPEG',
                                      options={'quality': 100})
    gallery_thumbnail = ImageSpecField(source='image',
                                   processors=[ResizeToFit(300, 250)],
                                   format='JPEG',
                                   options={'quality': 100})
    gallery_detail = ImageSpecField(source='image',
                                       processors=[ResizeToFit(1000, 850)],
                                       format='JPEG',
                                       options={'quality': 100})
    title = models.CharField(max_length=100)
    albums = models.ManyToManyField(Album, blank=True, related_name='photos')
    feature_image = models.BooleanField(default=False)
    description = models.CharField(editable=False, max_length=150, blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name='pictures')

    lens = models.TextField(editable=False, max_length=100, default='Lens Data')
    caption = models.CharField(editable=False, max_length=1000, default='Caption info')
    file_size = models.CharField(editable=False, max_length=20, default='File_size')
    width = models.IntegerField(blank=True, null=True, editable=False)
    height = models.IntegerField(blank=True, null=True, editable=False)
    categories = models.ForeignKey(Catagory, on_delete=models.CASCADE, null=True, blank=True)
    objects = models.Manager
    info = models.TextField(default='**info empty**', blank=True, help_text="editable caption info no reversable")
    exif = ExifField(source='image', denormalized_fields={'lens': exifgetter('LensID'),
                                                          'caption': exifgetter('Description'),
                                                          'file_size': exifgetter('FileSize'),
                                                          'description': exifgetter('Headline')

                                                          })


    def save(self, *args, **kwargs):
        super(Photo, self).save(*args, **kwargs)
        """Get EXIF"""
        im = Image.open(self.image)
        try:
            info = im.getexif()[0x010e]
            self.info = info
        except KeyError:
            pass
        super(Photo, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def albums_(self):
        lst = [x[1] for x in self.albums.values_list()]
        return ",".join(lst)

    def size(self):
         return "%s x %s" % (self.width, self.height)

blog/myblog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()



class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment, Photo, Album, Author
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm, ContactForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.views.generic.dates import ArchiveIndexView
from django.contrib import messages




def purchase_page(request):
    return render(request, 'post/purchase.html')








def contact_form(request):
    contact = Author.objects.get(name='Robert Melen')
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            send_mail(name, message, email, ['admin@blog.com'])
            messages.success(request, 'Your message has been sent, I will reply asap!')
            return HttpResponseRedirect(request.path_info)

    return render(request, 'post/contact_form.html', {'form': form,
                                                      'contact': contact})







#blog post views


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # list of active comments for this post
    comments = post.comments.filter(active=True)
    paginator = Paginator(comments, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #create comment object but dont save to database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            #save the comment to the database
            new_comment.save()
            messages.success(request, 'Your message has been sent, I will reply asap!.')
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'post/detail.html',
                  {'post': post,
                   'posts' : posts,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts,
                   })


class PostFeaturedView(ListView):
    queryset = Post.feature.all()
    context_object_name = 'featured'
    paginate_by = 3
    template_name = 'post/featured.html'


#form views

def post_share(request, post_id):
    #retrieve posts by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        #form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #form fields pass validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                          f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else: #.....send email
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                                'form': form,
                                                'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')

            search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query),
                                              ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'post/search.html',
                  {'form' : form,
                   'query' : query,
                   'results' : results})



def gallery_list(request):
    gallery = Album.objects.filter(public=True)
    paginator = Paginator(gallery, 4)
    page = request.GET.get('page')
    try:
        galleries = paginator.page(page)
    except PageNotAnInteger:
        galleries = paginator.page(1)
    except EmptyPage:
        galleries = paginator.page(paginator.num_pages)

    return render(request, 'gallery/gallery_list.html', {

        'galleries': galleries,
        })


def gallery_detail(request, gallery, pk):

    gallery = get_object_or_404(Album, slug=gallery, pk=pk)
    images = gallery.photos.all()
    return render(request,  'gallery/gallery_detail.html', {
                  'gallery': gallery,
    'images': images
    })

blog/myblog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
{% load widget_tweaks %}
{% include "blog/scripts.html" %}
 <style>
    a { color: black; } /* CSS link color */
 </style>
{% include "blog/nav_bar.html" %}
{% block header %}
        <div class="container" style="background-color: #E8E8E8;" >
            <div class="row">
                <div class="twelve columns" style="text-align: center; clear: right;
                 margin-top: 10px; background-color: white; ">
                    <h6 style="color:black;">{% now "jS F Y" %}</h6>
                    <h3 style="letter-spacing: 1px; position:relative; top:5px; ">
                        <i>Blog</i> by photographer/<strong>Robert Melen</strong></h3>
                    <h6 style="font-family:Georgia;">Welcome to my Blog/I wrote this using the Django framework written in Python. There are {% total_posts %} published articles</h6>
                     {% for images in image_featured %}
                    <img src="{{images.mid_thumbnail.url }}" style="max-height: 400px;"/>
                    {% endfor %}
                    <h6>Subscribe</h6>
                    <hr class="solid">
                </div>
            </div>
        </div>
{% endblock %}

<body>
        <div class="container">
            <div class="row">
                <div class="twelve columns" style="position:relative;top:30px; text-align: center;
                 background-color: white;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
         <div class="container">
            <div class="row">
                <div class="twelve columns" style=" text-align: center;">
                   {% include "blog/footer.html" %}
                </div>
            </div>
        </div>
</body>
<script src="{% static "js/gh.js" %}"></script>

{% include "blog/js.html" %}
</html>

blog/myblog/templates/blog/blogpage.html
{% load blog_tags %}
<div class="container" style="background: rgb(255, 255, 255);>
            <div class="row">
                <div class="twelve columns" style="text-align: center; top: 1x; position: relative; ">
                    <h6>Featured Posts</h6>
                    {% featured_posts 5 %}
                </div>

            </div>
        </div>

blog/myblog/templates/blog/footer.html
<div>

  <hr>
  <p>© Robert Melen 2022</p>
</div>

blog/myblog/templates/blog/js.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="{% static "js/gh.js" %}"></script>
<script src="/static/js/click.js"></script>
<script src="/static/js/sticky.js"></script>

blog/myblog/templates/blog/nav_bar.html
{% load blog_tags %}
<nav class="nav-show navbar-default" >
    <div class="container">
        <ul>
            <li><a href="{% url 'myblog:post_list' %}">Home</a></li>
            <li>
                <a>Images</a>
                <ul>
                    <li><a href="{% url 'myblog:gallery_list' %}">Galleries</a></li>
                    <li><a href="{% url 'myblog:purchase' %}">License/Purchase</a></li>
                </ul>
            </li>
            <li><a href="{% url 'myblog:contact_form' %}">Contact</a></li>
            <li>
                <a href="{% url 'myblog:post_archive' %}">Blog Archive</a>
            </li>
            </li>
            <li class="u-pull-right" style="padding: 1%;"><a class="button button-primary" href="#login">Client Login</a></li>
            <li class="right" style="padding: 1%;" ><a class="button button-primary" href="#register">Register</a></li>
            <li class="icon">
                <a href="javascript:void(0);" onclick="toggleMobileNav();">&#9776;</a>
            </li>
        </ul>
    </div>
</nav>

blog/myblog/templates/blog/scripts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="google-site-verification" content="GTZLLZUnqYh5zUYcOU9C0yM8olcX5rSUe31rU-6pv6M" />
        <meta charset="utf-8">
        {% block title %}
        <title>Robert Melen Blog</title>
        {% endblock %}
        <meta name="description" content="Photographer Robert Melen Blog">
        <meta name="author" content="Robert Melen">

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="//fonts.googleapis.com/css?family=Roboto:400,300,600" rel="stylesheet" type="text/css">
        <script src="https://kit.fontawesome.com/4f1d51e9c6.js" crossorigin="anonymous"></script>
        <link href="{% static "css/normalize.css" %}"rel="stylesheet">
        <link href="{% static "css/skeleton.css" %}"rel="stylesheet">
        <link href="{% static "css/gh.css" %}"rel="stylesheet">
        <link href="{% static "css/custom.css" %}"rel="stylesheet">


        <link rel="icon" type="image/png" href="images/favicon.png">
    </head>